### ISSUE TITLE
Example Oauth

### ISSUE THREAD

**Issue by hictdeveloper** [Seacommerce/multivers-sdk-php#7]
Dear,

Do you have a example script for getting the access token via the autorization (client identifier etc.)? (Or an explanation)
I can't connect well.

Thanks in advance.
Kindly regards.

**Comment by smoelker** [comment]
Hi hictdeveloper,

To get an access token you first need to acquire a refresh token. Please see the Unit4 documentation: https://api.online.unit4.nl/V110/Documentation/Guide/OAuth

Once you got the refresh token you can request an access token using this example

```php
use GuzzleHttp\Client;

$clientId = "YOUR_CLIENT_ID";
$clientSecret = "YOUR_CLIENT_SECRET";
$redirectUri = "https://path.to/your/own?redirect=url";
$refreshToken = "YOUR_REFRESH_TOKEN";
$url = "https://sandbox.api.online.unit4.nl/v110/";

$authClient = new Client([
    'base_uri' => $url,
]);
$tokenData = json_decode($authClient->post('OAuth/Token', [
    'form_params' => [
        'refresh_token' => $refreshToken,
        'client_id' => $clientId,
        'client_secret' => $clientSecret,
        'redirect_uri' => $redirectUri,
        'grant_type' => 'refresh_token',
    ],
    'headers' => [
        'Accept'     => 'application/json',
    ]
])->getBody()->getContents(), true);

$accessToken = $tokenData['access_token'];
```

**Comment by hictdeveloper** [comment]
Amazing! Thank you.

**Comment by hictdeveloper** [comment]
Dear, 

I get this error when I am trying to get the customers. I have followed your code as above for the access token. But it seems that the Access token is not working.

Exception when calling CustomerInfoListApi->getCustomerInfoList: [403] Client error: `GET https://sandbox.api.online.unit4.nl/v110/api/MVL46549/CustomerInfoList` resulted in a `403 Forbidden` response: Exception of type 'DotNetOpenAuth.Messaging.ProtocolFaultResponseException' was thrown.

Hope to hear from you soon.

**Comment by hictdeveloper** [comment]
If I copy the generated Access token from the API Help page to the script, it works. But when I, get an access token via the script you send above, the access token is not working.

**Comment by hictdeveloper** [comment]
`<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
// LOAD ALL DIRECTORIES
require_once('../../../vendor/autoload.php');
use GuzzleHttp\Client;

// RETRIEVE USER LOGGED IN SESSION
include('../../php/session.php');

// GET DATA OF USER FROM DATABASE
$get_client = mysqli_query($connection, "SELECT * FROM `users` WHERE `token`='$client_token' AND `setup`=0");
$client = mysqli_fetch_array($get_client);
$setup_token = $client['login_token'];

// GET THE API DETAILS
$api_sec = explode(',', $client['api_security']);

// DOING SCRIPT GIVEN FROM GITHUB
$clientId = $api_sec[0];
$clientSecret = $api_sec[1];
$redirectUri = "https://tirecenter.arutis.com/assets/api/UNIT4/connectAPI.php";
$refreshToken = $api_sec[2];
$url = "https://sandbox.api.online.unit4.nl/v110/";

$authClient = new Client([
    'base_uri' => $url,
]);
$tokenData = json_decode($authClient->post('OAuth/Token', [
    'form_params' => [
        'refresh_token' => $refreshToken,
        'client_id' => $clientId,
        'client_secret' => $clientSecret,
        'redirect_uri' => $redirectUri,
        'grant_type' => 'refresh_token',
    ],
    'headers' => [
        'Accept'     => 'application/json',
    ]
])->getBody()->getContents(), true);

// GET NEW TOKENS
$refresh_token = $tokenData['refresh_token'];
$access_token = $tokenData['access_token'];

// STORE NEW TOKENS IN DATABASE
$new_api_security = $api_sec[0] . ',' . $api_sec[1] . ',' . $refresh_token . ',' . $access_token;
$update_client = mysqli_query($connection, "UPDATE `users` SET `api_security`='$new_api_security' WHERE `token`='$client_token'");
if($update_client) {
    echo 'Authorisatie gelukt! <br /><br />';

} else {
    echo 'Authorisatie mislukt! <br /><br />';
}

// Configure OAuth2 access token for authorization: production
$config = Seacommerce\Unit4\Multivers\Sdk\Configuration::getDefaultConfiguration()->setAccessToken($access_token);

$apiInstance = new Seacommerce\Unit4\Multivers\Sdk\Api\CustomerInfoListApi(
    // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
    // This is optional, `GuzzleHttp\Client` will be used as default.
    new GuzzleHttp\Client(),
    $config
);
$database = 'MVL46549'; 


try {
    $result = $apiInstance->getCustomerInfoList($database);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling CustomerInfoListApi->getCustomerInfoList: ', $e->getMessage(), PHP_EOL;
}
?>`

**Comment by hictdeveloper** [comment]
I think there is some data missing. The access tokens I receive via my code always have 891 characters, while the access tokens generated by the 'API Help' page have 976 characters.

Do you know how to solve this?

**Comment by smoelker** [comment]
I can't reproduce the error with the code example you provided. After stripping the session and mysql related sections and pasting in my own client credentials, I got the customer info list as expected.

Are you sure the refresh token in your database was generated for the right user (the same user you're using to test though the 'Api Help' pages)?

**Comment by hictdeveloper** [comment]
Thanks for helping. I am using the exact same user as registered and the client credentials given on the 'Mijn applicaties' page. It is weird that my access token only has 891 characters, isn't it?

**Comment by hictdeveloper** [comment]
I think I see the problem. I think my application deleted itself, if that is actually possible? Haha, contacting UNIT4 now. I will keep you updated.

**Comment by hictdeveloper** [comment]
Was not the problem. Could I send you my code and client credentials (It is just a test account) via the mail? If you can help me, I'll buy you a beer :)

**Comment by smoelker** [comment]
Yeah, sure. You can find my email address on my profile page.

**Comment by Casmo** [comment]
For those coming from Google: The access token is shorter probably because you didn't include the 'scope' parameter in the request.
